# ==================== kubernetes/ingress.yaml ====================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot-ingress
  namespace: bot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bot.yourdomain.com
    secretName: bot-tls
  rules:
  - host: bot.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bot-api
            port:
              number: 80
      - path: /webhook
        pathType: Exact
        backend:
          service:
            name: bot-api
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
  namespace: bot
data:
  config.yaml: |
    environment: production
    log_level: INFO
    enable_monitoring: true
    enable_cache: true
    rate_limits:
      per_user: "10/minute"
      global: "1000/minute"
---
apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
  namespace: bot
type: Opaque
data:
  bot-token: <base64-encoded-token>
  database-url: <base64-encoded-url>
  redis-url: <base64-encoded-url>
  celery-broker-url: <base64-encoded-url>